---
- name: Install packages
  apt:
    name: "{{ item }}"
  with_items:
    - vim
    - arandr
    - feh
    - compton
    - rofi
    - lxappearance
    - i3
    - i3lock
    - i3blocks
    - git
    - golang
    - python3
    - python-pip
    - python-dev
    - libmysqlclient-dev
    - xbacklight
    - acpi
    - libanyevent-i3-perl

- name: Install i3-gaps
  command: /home/{{ deb_username }}/deb-ansible/roles/packages/files/i3gaps-install.sh
