---
- name: Install packages
  apt:
    name: "{{ item }}"
  with_items:
    - arandr
    - feh
    - compton
    - rofi
    - lxappearance
    - i3-gaps
    - i3blocks
    - git
    - go
    - python
    - python-pip
    - python-dev
    - libmysqlclient
