---
- name: Install packages
  apt:
    name: "{{ item }}"
  with_items:
    - vim
    - arandr
    - feh
    - compton
    - rofi
    - lxappearance
    - i3blocks
    - git
    - go
    - python
    - python-pip
    - python-dev
    - libmysqlclient

- name: Install i3-gaps
  command: /home/{{ deb_username }}/deb-ansible/roles/packages/files/i3gaps-install.sh
