---
- name: Create config directory
  file:
    path: /home/{{ deb_username }}/{{ item }}
    state: directory
    owner: "{{ deb_username }}"
    group: "{{ deb_username }}"
  with_items:
    - .config
    - .config/i3

- name: Install i3 config
  template:
    src: i3_config
    dest: /home/{{ deb_username }}/.config/i3/config
    owner: "{{ deb_username }}"
    group: "{{ deb_username }}"

- name: Install i3blocks config
  copy:
    src: i3blocks.conf
    dest: /home/{{ deb_username }}/.config/i3/i3blocks.conf
    owner: "{{ deb_username }}"
    group: "{{ deb_username }}"

- name: Copy .Xresources and wallpaper into place
  copy:
    src: "{{ item ]}"
    dest: /home/{{ deb_username }}/
    owner: "{{ deb_username }}"
    group: "{{ deb_username }}"
  with_items:
    - wallpaper.jpg
    - .Xresources
