---
- name: Create fonts directory
  file:
    path: /home/{{ deb_username }}/{{ item }}
    state: directory
    owner: "{{ deb_username }}"
    group: "{{ deb_username }}"
    mode: 0755
  with_items:
    - .fonts
    - tmp

- name: Unzip System San Francisco
  unarchive:
    src: "{{ item }}"
    dest: /home/{{ deb_username }}/tmp/
  with_items:
    - YosemiteSanFranciscoFont-master.zip
    - Input-Font.zip

- name: Install System San Francisco
  copy:
    src: /home/{{ deb_username }}/tmp/YosemiteSanFranciscoFont-master/*.ttf
    dest: /home/{{ deb_username }}/.fonts/
    owner: "{{ deb_username }}"
    group: "{{ deb_username }}"
    mode: 0755

- name: Install Input
  copy:
    src: /home/{{ deb_username }}/tmp/Input_Fonts/InputMono/InputMonoNarrow/*.ttf
    dest: /home/{{ deb_username }}/.fonts/
    owner: "{{ deb_username }}"
    group: "{{ deb_username }}"
    mode: 0755
